Added css file
Piotr-code-tech/learning-app pull request #2
Opened 2021-06-14 16:16 UTC by Piotr-code-tech

I added css file and closed recent branch. Now I working on the css of the site.

2021-06-14 21:49 UTC, Piotr-code-tech commented
I added css file and linked it in html file. I also changed strong tag to p tag - I'll make it bold in css. And I split div tag for outputs into two tags for net and gross value.  In .css file I wrote some lines but it isn't everything.

2021-06-19 12:25 UTC, Piotr-code-tech commented
Hi Patryk, I worked at font and background color, now I'm working on the position of elements, I used flexbox and I don't know if I should use one or more flexbox element, I want to put main heading in top left corner and all calculator in the middle of page but when I use one flexbox element i have problem to separate heading and calculator. Maybe I should use a grid elements ?

2021-06-24 14:10 UTC, pstudniak requested changes

2021-06-28 08:33 UTC, pstudniak approved these changes

2021-06-28 08:33 UTC, pstudniak commented on src/style.css
> +background-color: silver;
Let's add a prettier/formatter and ES Linter to your Project in next Pull Request. We can group up on that. Please read about ES Lint and Prettier. We'll avoid formatting/code style issues when we start on JavaScript.

2021-06-28 16:41 UTC, merged