List items and some changes in js
Piotr-code-tech/learning-app pull request #6
Opened 2021-10-04 19:16 UTC by Piotr-code-tech

2021-11-04 10:54 UTC, pstudniak requested changes
This PR looks good overall. Now we will transist it to app with build system. We will split files logically so we could get rid of any comments from the code that are organising structure so far. 

Please apply requested changes and merge PR. 

Thanks!

2021-11-04 10:54 UTC, pstudniak commented on src/calculator.js
> +const openWindowEvent = () => {
this event functions are redundant

2021-11-04 10:54 UTC, pstudniak commented on src/calculator.js
> +const closeWindowEvent = () => {
also apart from redundancy, those are not Events, those are Callbacks to Events

2021-11-04 10:54 UTC, pstudniak commented on src/index.html
> +                <button class = "calculateButton">Calculate</button>
no need for spaces in html attributes values assignment

2021-11-04 10:54 UTC, pstudniak commented on src/calculator.js
> +    deleteButton.innerHTML = "\u00D7";
? is it some kind of html entity?

2021-11-07 22:01 UTC, Piotr-code-tech commented on src/calculator.js
> +    deleteButton.innerHTML = "\u00D7";
it is a minus icon attached to the button

2021-11-07 22:15 UTC, Piotr-code-tech commented on src/index.html
> +                <button class = "calculateButton">Calculate</button>
okey, I think that code will be more readable, but you're right it isn't the best way

2021-11-10 10:44 UTC, merged